services:
  backend:
    image: viettel-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend/database:/app/backend/database
    environment:
      - PYTHONPATH=/app

  frontend:
    image: viettel-frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - frontend/.env